### ISSUE TITLE
¿Más propuestas o cerramos tema y dividimos tareas?

### ISSUE THREAD

**Issue by jestebango** [jestebango/uoc#4]
Propuestas para dividir el trabajo ¿Qué realiza cada uno?

**Comment by srodriguezcep** [comment]
Mi propuesta si os parece bien, podría ser según las propuestas que hemos realizado cada uno
Colaborador 1: Web scraping en https://www.ordenacionjuego.es/es/operadores/buscar de las empresas de acuerdo al criterio de búsqueda que decida. También web scraping de la dirección de cada empresa (al menos la zona geográfica, localidad y provincia). JOSE LUIS
Colaborador 3: Web scraping de estadísticas o indicadores relativos a tasas de criminalidad, número de condenas,.. por zonas.
http://www.poderjudicial.es/cgpj/es/Temas/Estadistica-Judicial/ (aportado por Carlos) CARLOS

Colaborador 2: Web scraping de estadísticas o indicadores relativas a los diferentes servicios públicos que existen en la zona (número de colegios, hospitales, salario medio,..); en fin, lo que se le ocurra.
http://www.ine.es/jaxiT3/Tabla.htm?t=2852&L=0 (aportado por María; población, padrón,...) SONIA

Os parece bien.

**Comment by estratic** [comment]
Hola de nuevo,
Respecto de la tarea de Colaborador 3: El único problema que me puedo encontrar es el permiso para abordar el tema de justicia, como comenté. Una opción que podría ser interesante para mi –para cubrirme las espaldas- es recoger los compromisos de los países con la alianza para el gobierno abierto en materia de justicia. El ámbito será internacional.
Así pues, mi propuesta concreta para Colaborador 3 es:
Web scraping de compromisos de los países con la alianza para el gobierno abierto en materia de justicia  
La web sería http://www.opengovpartnership.org/explorer/all-data.html
