### ISSUE TITLE
Comenzamos!!

### ISSUE THREAD

**Issue by jestebango** [jestebango/uoc#6]
Tareas asignadas:

srodriguezcep: Web scraping de variables estadísticas (INE)
estratic: Web scraping de variables relacionadas con la justicia
jestebango: Web scraping de variables relacionadas con empresas de apuestas

Deadline: ver milestones (OK?)

**Comment by srodriguezcep** [comment]
Ok. Perfecto!!!!!!!!!!!! Le pasas el link a la profe con la propuesta?. Gracias
PD: Nos pones copia en el e-mail.

**Comment by jestebango** [comment]
Si quieres enviarle algo a la tutora, por mi perfecto. En teoría sólo está el deadline de la fecha de entrega.

**Comment by srodriguezcep** [comment]
Muchas gracias Jose Luis, por el envió del e-mail.
